debian: postinst: ensure /etc/iproute2/rt_tables.d exists
When upgrading to Debian Trixie, iproute2 is also upgraded. Its
postinst deletes /etc/iproute2/rt_tables.d if it is currently empty
(or only contains a README file) [1]. After that, ifreload -a will
always print a warning:

> error: [Errno 2] No such file or directory: '/etc/iproute2/rt_tables.d/ifupdown2_vrf_map.conf'

because it cannot create the file if the parent directory does not
exist.

To avoid that, create the directory in ifupdown2's postinst if it
does not exist yet.

Commit b115f7f ("add /etc/iproute2/rt_tables.d/ to managed
directories") already added the directory to ifupdown2.dirs, but this
does not seem to be effective, due to the following sequence of events
on upgrade:

1) iproute2 is unpacked
2) ifupdown2 is unpacked. The directory still exists, so the
   ifupdown2.dirs entry does not have an effect
3) ifroute2 is set up, and its postinst empties and removes the
   directory
4) ifupdown2 is set up

[1] https://sources.debian.org/src/iproute2/6.15.0-1/debian/iproute2.postinst/

Signed-off-by: Friedrich Weber <f.weber@proxmox.com>
Tested-by: Michael Köppl <m.koeppl@proxmox.com>
Link: https://lore.proxmox.com/20250708164344.104855-1-f.weber@proxmox.com